config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
    validates :name, :address, presence: true
    validates :category, inclusion: {in: CATEGORIES}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: [0, 1, 2, 3, 4, 5]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show]

    def index
        @restaurants = Restaurant.all
    end

    def show
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to @restaurant, notice: 'Restaurant was successfully created.'
        else
            render :new
        end
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.restaurant = @restaurant
        if @review.save
          redirect_to restaurant_path(@restaurant)
        else
          render :new
        end
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end
    
    def review_params
        params.require(:review).permit(:rating, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs m-3">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions btn btn-primary m-3">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>

<p><%= link_to "Add a restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h2>Add a new restaurant</h2>

<%= render 'form', article: @restaurant %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p><%= link_to "Add a review", new_restaurant_review_path(@restaurant) %></p>

app/views/reviews/new.html.erb
<h2>Add a new review</h2>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs m-3">
    <%= f.input :rating %>
    <%= f.input :content %>
  </div>

  <div class="form-actions btn btn-primary m-3">
    <%= f.button :submit %>
  </div>
<% end %>